### ISSUE TITLE
Compile failure w/ pre-AMP base

### ISSUE THREAD

**Issue by hvr** [SamuelSchlesinger/gross#2]
The compile failure below occurs with base < 4.8; unless you want to support base < 4.8 it's easiest to set a tighter lower bound `base >= 4.8`

```
Configuring component lib from gross-0.0.0.0...
Preprocessing library gross-0.0.0.0...
[1 of 1] Compiling Graphics.Gross   ( Graphics/Gross.hs, /tmp/matrix-worker/1484503254/dist-newstyle/build/x86_64-linux/ghc-7.8.4/gross-0.0.0.0/build/Graphics/Gross.o )

Graphics/Gross.hs:17:7: Not in scope: ‘pure’
```

I've fixed up the metadata on Hackage already and I've also set `bug-reports: https://github.com/SamuelSchlesinger/gross/issues` to make it easier to find this issue tracker:

 - https://hackage.haskell.org/package/gross-0.0.0.0/revisions/

**Comment by SamuelSchlesinger** [comment]
Yeah that's perfect, thanks a lot! I'll change it on here

**Comment by SamuelSchlesinger** [comment]
Fixed it :+1:
